//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodOkuApi
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BarkodSonuc", Namespace="http://barkodoku.com/")]
    public partial class BarkodSonuc : object
    {
        
        private BarkodOkuApi.Barkod UrunBarkodField;
        
        private BarkodOkuApi.Hata HataMesajiField;
        
        private BarkodOkuApi.BarkodCozum BarkodCozumuField;
        
        private BarkodOkuApi.KotaBilgi KotaBilgisiField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public BarkodOkuApi.Barkod UrunBarkod
        {
            get
            {
                return this.UrunBarkodField;
            }
            set
            {
                this.UrunBarkodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public BarkodOkuApi.Hata HataMesaji
        {
            get
            {
                return this.HataMesajiField;
            }
            set
            {
                this.HataMesajiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public BarkodOkuApi.BarkodCozum BarkodCozumu
        {
            get
            {
                return this.BarkodCozumuField;
            }
            set
            {
                this.BarkodCozumuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public BarkodOkuApi.KotaBilgi KotaBilgisi
        {
            get
            {
                return this.KotaBilgisiField;
            }
            set
            {
                this.KotaBilgisiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Barkod", Namespace="http://barkodoku.com/")]
    public partial class Barkod : object
    {
        
        private string UrunBarkodField;
        
        private string UrunAdField;
        
        private string UrunDetayField;
        
        private string BarkodTipField;
        
        private BarkodOkuApi.Firma UreticiField;
        
        private BarkodOkuApi.Fiyat[] UrunFiyatField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UrunBarkod
        {
            get
            {
                return this.UrunBarkodField;
            }
            set
            {
                this.UrunBarkodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UrunAd
        {
            get
            {
                return this.UrunAdField;
            }
            set
            {
                this.UrunAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UrunDetay
        {
            get
            {
                return this.UrunDetayField;
            }
            set
            {
                this.UrunDetayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BarkodTip
        {
            get
            {
                return this.BarkodTipField;
            }
            set
            {
                this.BarkodTipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public BarkodOkuApi.Firma Uretici
        {
            get
            {
                return this.UreticiField;
            }
            set
            {
                this.UreticiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public BarkodOkuApi.Fiyat[] UrunFiyat
        {
            get
            {
                return this.UrunFiyatField;
            }
            set
            {
                this.UrunFiyatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hata", Namespace="http://barkodoku.com/")]
    public partial class Hata : object
    {
        
        private string HataKoduField;
        
        private string HataAciklamaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HataAciklama
        {
            get
            {
                return this.HataAciklamaField;
            }
            set
            {
                this.HataAciklamaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BarkodCozum", Namespace="http://barkodoku.com/")]
    public partial class BarkodCozum : object
    {
        
        private string MenseiField;
        
        private int UreticiKoduField;
        
        private int UrunKoduField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensei
        {
            get
            {
                return this.MenseiField;
            }
            set
            {
                this.MenseiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UreticiKodu
        {
            get
            {
                return this.UreticiKoduField;
            }
            set
            {
                this.UreticiKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UrunKodu
        {
            get
            {
                return this.UrunKoduField;
            }
            set
            {
                this.UrunKoduField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KotaBilgi", Namespace="http://barkodoku.com/")]
    public partial class KotaBilgi : object
    {
        
        private int KalanKotaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int KalanKota
        {
            get
            {
                return this.KalanKotaField;
            }
            set
            {
                this.KalanKotaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Firma", Namespace="http://barkodoku.com/")]
    public partial class Firma : object
    {
        
        private string FirmaAdiField;
        
        private string FirmaAdresField;
        
        private string FirmaSehirField;
        
        private string FirmaIlceField;
        
        private string FirmaTelefonField;
        
        private string FirmaFaksField;
        
        private string Firma444Field;
        
        private string FirmaSektorField;
        
        private string FirmaWebField;
        
        private string FirmaLogoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirmaAdi
        {
            get
            {
                return this.FirmaAdiField;
            }
            set
            {
                this.FirmaAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirmaAdres
        {
            get
            {
                return this.FirmaAdresField;
            }
            set
            {
                this.FirmaAdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirmaSehir
        {
            get
            {
                return this.FirmaSehirField;
            }
            set
            {
                this.FirmaSehirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FirmaIlce
        {
            get
            {
                return this.FirmaIlceField;
            }
            set
            {
                this.FirmaIlceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FirmaTelefon
        {
            get
            {
                return this.FirmaTelefonField;
            }
            set
            {
                this.FirmaTelefonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FirmaFaks
        {
            get
            {
                return this.FirmaFaksField;
            }
            set
            {
                this.FirmaFaksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Firma444
        {
            get
            {
                return this.Firma444Field;
            }
            set
            {
                this.Firma444Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string FirmaSektor
        {
            get
            {
                return this.FirmaSektorField;
            }
            set
            {
                this.FirmaSektorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string FirmaWeb
        {
            get
            {
                return this.FirmaWebField;
            }
            set
            {
                this.FirmaWebField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string FirmaLogo
        {
            get
            {
                return this.FirmaLogoField;
            }
            set
            {
                this.FirmaLogoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fiyat", Namespace="http://barkodoku.com/")]
    public partial class Fiyat : object
    {
        
        private double UrunFiyatField;
        
        private System.DateTime FiyatTarihField;
        
        private BarkodOkuApi.Mekan FiyatMekanField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double UrunFiyat
        {
            get
            {
                return this.UrunFiyatField;
            }
            set
            {
                this.UrunFiyatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime FiyatTarih
        {
            get
            {
                return this.FiyatTarihField;
            }
            set
            {
                this.FiyatTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public BarkodOkuApi.Mekan FiyatMekan
        {
            get
            {
                return this.FiyatMekanField;
            }
            set
            {
                this.FiyatMekanField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mekan", Namespace="http://barkodoku.com/")]
    public partial class Mekan : object
    {
        
        private string MekanAdiField;
        
        private string MekanAdresField;
        
        private string MekanSehirField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MekanAdi
        {
            get
            {
                return this.MekanAdiField;
            }
            set
            {
                this.MekanAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MekanAdres
        {
            get
            {
                return this.MekanAdresField;
            }
            set
            {
                this.MekanAdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MekanSehir
        {
            get
            {
                return this.MekanSehirField;
            }
            set
            {
                this.MekanSehirField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://barkodoku.com/", ConfigurationName="BarkodOkuApi.BarkodServisSoap")]
    public interface BarkodServisSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barkodoku.com/Merhaba", ReplyAction="*")]
        System.Threading.Tasks.Task<BarkodOkuApi.MerhabaResponse> MerhabaAsync(BarkodOkuApi.MerhabaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barkodoku.com/BarkodGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<BarkodOkuApi.BarkodGetirResponse> BarkodGetirAsync(BarkodOkuApi.BarkodGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barkodoku.com/KotaSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<BarkodOkuApi.KotaSorgulaResponse> KotaSorgulaAsync(BarkodOkuApi.KotaSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barkodoku.com/QRKodOlustur", ReplyAction="*")]
        System.Threading.Tasks.Task<BarkodOkuApi.QRKodOlusturResponse> QRKodOlusturAsync(BarkodOkuApi.QRKodOlusturRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MerhabaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Merhaba", Namespace="http://barkodoku.com/", Order=0)]
        public BarkodOkuApi.MerhabaRequestBody Body;
        
        public MerhabaRequest()
        {
        }
        
        public MerhabaRequest(BarkodOkuApi.MerhabaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MerhabaRequestBody
    {
        
        public MerhabaRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MerhabaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MerhabaResponse", Namespace="http://barkodoku.com/", Order=0)]
        public BarkodOkuApi.MerhabaResponseBody Body;
        
        public MerhabaResponse()
        {
        }
        
        public MerhabaResponse(BarkodOkuApi.MerhabaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class MerhabaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerhabaResult;
        
        public MerhabaResponseBody()
        {
        }
        
        public MerhabaResponseBody(string MerhabaResult)
        {
            this.MerhabaResult = MerhabaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BarkodGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BarkodGetir", Namespace="http://barkodoku.com/", Order=0)]
        public BarkodOkuApi.BarkodGetirRequestBody Body;
        
        public BarkodGetirRequest()
        {
        }
        
        public BarkodGetirRequest(BarkodOkuApi.BarkodGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class BarkodGetirRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string barkod;
        
        public BarkodGetirRequestBody()
        {
        }
        
        public BarkodGetirRequestBody(string apiKey, string barkod)
        {
            this.apiKey = apiKey;
            this.barkod = barkod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BarkodGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BarkodGetirResponse", Namespace="http://barkodoku.com/", Order=0)]
        public BarkodOkuApi.BarkodGetirResponseBody Body;
        
        public BarkodGetirResponse()
        {
        }
        
        public BarkodGetirResponse(BarkodOkuApi.BarkodGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class BarkodGetirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BarkodOkuApi.BarkodSonuc BarkodGetirResult;
        
        public BarkodGetirResponseBody()
        {
        }
        
        public BarkodGetirResponseBody(BarkodOkuApi.BarkodSonuc BarkodGetirResult)
        {
            this.BarkodGetirResult = BarkodGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KotaSorgulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KotaSorgula", Namespace="http://barkodoku.com/", Order=0)]
        public BarkodOkuApi.KotaSorgulaRequestBody Body;
        
        public KotaSorgulaRequest()
        {
        }
        
        public KotaSorgulaRequest(BarkodOkuApi.KotaSorgulaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class KotaSorgulaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        public KotaSorgulaRequestBody()
        {
        }
        
        public KotaSorgulaRequestBody(string apiKey)
        {
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KotaSorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KotaSorgulaResponse", Namespace="http://barkodoku.com/", Order=0)]
        public BarkodOkuApi.KotaSorgulaResponseBody Body;
        
        public KotaSorgulaResponse()
        {
        }
        
        public KotaSorgulaResponse(BarkodOkuApi.KotaSorgulaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class KotaSorgulaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int KotaSorgulaResult;
        
        public KotaSorgulaResponseBody()
        {
        }
        
        public KotaSorgulaResponseBody(int KotaSorgulaResult)
        {
            this.KotaSorgulaResult = KotaSorgulaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QRKodOlusturRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QRKodOlustur", Namespace="http://barkodoku.com/", Order=0)]
        public BarkodOkuApi.QRKodOlusturRequestBody Body;
        
        public QRKodOlusturRequest()
        {
        }
        
        public QRKodOlusturRequest(BarkodOkuApi.QRKodOlusturRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class QRKodOlusturRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string veri;
        
        public QRKodOlusturRequestBody()
        {
        }
        
        public QRKodOlusturRequestBody(string apiKey, string veri)
        {
            this.apiKey = apiKey;
            this.veri = veri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QRKodOlusturResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QRKodOlusturResponse", Namespace="http://barkodoku.com/", Order=0)]
        public BarkodOkuApi.QRKodOlusturResponseBody Body;
        
        public QRKodOlusturResponse()
        {
        }
        
        public QRKodOlusturResponse(BarkodOkuApi.QRKodOlusturResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class QRKodOlusturResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QRKodOlusturResult;
        
        public QRKodOlusturResponseBody()
        {
        }
        
        public QRKodOlusturResponseBody(string QRKodOlusturResult)
        {
            this.QRKodOlusturResult = QRKodOlusturResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface BarkodServisSoapChannel : BarkodOkuApi.BarkodServisSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class BarkodServisSoapClient : System.ServiceModel.ClientBase<BarkodOkuApi.BarkodServisSoap>, BarkodOkuApi.BarkodServisSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BarkodServisSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BarkodServisSoapClient.GetBindingForEndpoint(endpointConfiguration), BarkodServisSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BarkodServisSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BarkodServisSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BarkodServisSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BarkodServisSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BarkodServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }


        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BarkodOkuApi.MerhabaResponse> BarkodOkuApi.BarkodServisSoap.MerhabaAsync(BarkodOkuApi.MerhabaRequest request)
        {
            return base.Channel.MerhabaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BarkodOkuApi.MerhabaResponse> MerhabaAsync()
        {
            BarkodOkuApi.MerhabaRequest inValue = new BarkodOkuApi.MerhabaRequest();
            inValue.Body = new BarkodOkuApi.MerhabaRequestBody();
            return ((BarkodOkuApi.BarkodServisSoap)(this)).MerhabaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BarkodOkuApi.BarkodGetirResponse> BarkodOkuApi.BarkodServisSoap.BarkodGetirAsync(BarkodOkuApi.BarkodGetirRequest request)
        {
            return base.Channel.BarkodGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<BarkodOkuApi.BarkodGetirResponse> BarkodGetirAsync(string apiKey, string barkod)
        {
            BarkodOkuApi.BarkodGetirRequest inValue = new BarkodOkuApi.BarkodGetirRequest();
            inValue.Body = new BarkodOkuApi.BarkodGetirRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.barkod = barkod;
            return ((BarkodOkuApi.BarkodServisSoap)(this)).BarkodGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BarkodOkuApi.KotaSorgulaResponse> BarkodOkuApi.BarkodServisSoap.KotaSorgulaAsync(BarkodOkuApi.KotaSorgulaRequest request)
        {
            return base.Channel.KotaSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BarkodOkuApi.KotaSorgulaResponse> KotaSorgulaAsync(string apiKey)
        {
            BarkodOkuApi.KotaSorgulaRequest inValue = new BarkodOkuApi.KotaSorgulaRequest();
            inValue.Body = new BarkodOkuApi.KotaSorgulaRequestBody();
            inValue.Body.apiKey = apiKey;
            return ((BarkodOkuApi.BarkodServisSoap)(this)).KotaSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BarkodOkuApi.QRKodOlusturResponse> BarkodOkuApi.BarkodServisSoap.QRKodOlusturAsync(BarkodOkuApi.QRKodOlusturRequest request)
        {
            return base.Channel.QRKodOlusturAsync(request);
        }
        
        public System.Threading.Tasks.Task<BarkodOkuApi.QRKodOlusturResponse> QRKodOlusturAsync(string apiKey, string veri)
        {
            BarkodOkuApi.QRKodOlusturRequest inValue = new BarkodOkuApi.QRKodOlusturRequest();
            inValue.Body = new BarkodOkuApi.QRKodOlusturRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.veri = veri;
            return ((BarkodOkuApi.BarkodServisSoap)(this)).QRKodOlusturAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BarkodServisSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BarkodServisSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BarkodServisSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.barkodoku.com/ws/BarkodServis.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BarkodServisSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.barkodoku.com/ws/BarkodServis.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BarkodServisSoap,
            
            BarkodServisSoap12,
        }
    }
}
